### ISSUE TITLE
tests for fully_connected function

### ISSUE THREAD

**Issue by lvecsey** [VivianoRiccardo/Learning-Lab-C-Library#1]
I was trying to run some of the tests like test1 through test6 and I'm noticing that fully_connected needs two extra parameters.
So I tried putting in for example 8, NO_NORMALIZATION as the last two parameters, however I don't know if that is supposed to work.
I'm able to compile however there is an Illegal instruction (core dumped) on my Ubuntu platform.
Specifically with a debugger it is showing that c->layer = layer in convolutional_layers.c is a problem.

**Comment by VivianoRiccardo** [comment]
i have to update each single test according to the new updates of the library i think i m gonna update today, i m gonna let you know when they are updated

**Comment by VivianoRiccardo** [comment]
Now the tests are up to date, i added on 23/3/2020 a normalization layer inside the fully connected layer and the tests were not updated according to the new feature. Now you can try them.
To compile the tests:
`gcc -o main main.c -lllab -lm -lpthread -O3 -mavx2 -g`

**Comment by VivianoRiccardo** [comment]
I have no core dumped on my linux, tell me which test give you the error
